### ISSUE TITLE
添加没有背景图时的设定

### ISSUE THREAD

**Issue by Nugine** [ntzx/GameEngine-Glue#1]
当没有背景图时，继承上一张背景
如果全都没有背景，把content-box的height设置成100%，description-container的height设置成39.2%

**Comment by losfair** [comment]
> 当没有背景图时，继承上一张背景

这应该在描述文件生成时完成，而不应该在运行时进行处理。否则可能破坏视图状态的一致性。

例如，如果游戏状态 C 既可以从 A 转移得来，又可以从 B 转移得来，此时游戏状态 C 下的视图状态（显示的背景图）就是不确定的。这很大程度上降低了用户体验的可控性。

> 如果全都没有背景，把content-box的height设置成100%，description-container的height设置成39.2%

如果真的要允许没有背景图的情况在**正式发布的版本**中出现，这样做是可以的。
